highlighter: rouge
gems: [jekyll-paginate]
encoding: utf-8
paginate: 8
paginate_path: "page:num"
markdown: kramdown
kramdown:
  syntax_highlighter: rouge

name: 这个名字想了一天
description: 总要写些什么！
url: https://zhuxiaoqiangcn.github.io/
email: zhuxiaoqianghitwh@gmail.com

defaults:
 -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      show_ad: true

navs:
  -
    href: /feed/
    label: 订阅
  -
    href: /about/
    label: 关于本站
  -
    href: /me/
    label: 关于作者
  -
    href: /articles/
    label: 归档

# ---------------- #
#      Socials     #
# ---------------- #
github_id: zhuxiaoqiangcn
weibo_id: 
zhihu_id: GMOnePoint